### ISSUE TITLE
Needs Variables.less

### ISSUE THREAD

**Issue by scottshane** [IberaSoft/bower-bootstrap-less#1]
doesnt work with out variable.less

**Comment by cpoliver** [comment]
Hi mate,

Please can you add this back in, otherwise it breaks our project.

The bootstrap.less requires variables.less in its own directory. Our overrides are loaded after bootstrap in main.less - otherwise it means changing all the paths in bootstrap's less files or copying our variables out of our src directory and into vendor, which is a no no.

Cheers,

Charlie
